/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'isPinned' : IDL.Bool,
});
export const Material = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'classNumber' : IDL.Nat,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'fileType' : IDL.Text,
  'uploadDate' : Time,
  'fileUrl' : IDL.Text,
});
export const SamplePaper = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'classNumber' : IDL.Nat,
  'subject' : IDL.Text,
  'year' : IDL.Nat,
  'uploadDate' : Time,
  'fileUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([Announcement], [], []),
  'addMaterial' : IDL.Func([Material], [], []),
  'addSamplePaper' : IDL.Func([SamplePaper], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
  'deleteSamplePaper' : IDL.Func([IDL.Nat], [], []),
  'generateId' : IDL.Func([], [IDL.Nat], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'getAllSamplePapers' : IDL.Func([], [IDL.Vec(SamplePaper)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMaterialsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Material)], ['query']),
  'getSamplePapersByYear' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SamplePaper)],
      ['query'],
    ),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAnnouncements' : IDL.Nat,
          'totalMaterials' : IDL.Nat,
          'totalPapers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAnnouncement' : IDL.Func([IDL.Nat, Announcement], [], []),
  'updateMaterial' : IDL.Func([IDL.Nat, Material], [], []),
  'updateSamplePaper' : IDL.Func([IDL.Nat, SamplePaper], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'isPinned' : IDL.Bool,
  });
  const Material = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'classNumber' : IDL.Nat,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'fileType' : IDL.Text,
    'uploadDate' : Time,
    'fileUrl' : IDL.Text,
  });
  const SamplePaper = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'classNumber' : IDL.Nat,
    'subject' : IDL.Text,
    'year' : IDL.Nat,
    'uploadDate' : Time,
    'fileUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([Announcement], [], []),
    'addMaterial' : IDL.Func([Material], [], []),
    'addSamplePaper' : IDL.Func([SamplePaper], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
    'deleteSamplePaper' : IDL.Func([IDL.Nat], [], []),
    'generateId' : IDL.Func([], [IDL.Nat], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'getAllSamplePapers' : IDL.Func([], [IDL.Vec(SamplePaper)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMaterialsByClass' : IDL.Func([IDL.Nat], [IDL.Vec(Material)], ['query']),
    'getSamplePapersByYear' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SamplePaper)],
        ['query'],
      ),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAnnouncements' : IDL.Nat,
            'totalMaterials' : IDL.Nat,
            'totalPapers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAnnouncement' : IDL.Func([IDL.Nat, Announcement], [], []),
    'updateMaterial' : IDL.Func([IDL.Nat, Material], [], []),
    'updateSamplePaper' : IDL.Func([IDL.Nat, SamplePaper], [], []),
  });
};

export const init = ({ IDL }) => { return []; };