/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'isPinned' : boolean,
}
export interface Material {
  'id' : bigint,
  'title' : string,
  'classNumber' : bigint,
  'subject' : string,
  'description' : string,
  'fileType' : string,
  'uploadDate' : Time,
  'fileUrl' : string,
}
export interface SamplePaper {
  'id' : bigint,
  'title' : string,
  'classNumber' : bigint,
  'subject' : string,
  'year' : bigint,
  'uploadDate' : Time,
  'fileUrl' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[Announcement], undefined>,
  'addMaterial' : ActorMethod<[Material], undefined>,
  'addSamplePaper' : ActorMethod<[SamplePaper], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteMaterial' : ActorMethod<[bigint], undefined>,
  'deleteSamplePaper' : ActorMethod<[bigint], undefined>,
  'generateId' : ActorMethod<[], bigint>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getAllSamplePapers' : ActorMethod<[], Array<SamplePaper>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaterialsByClass' : ActorMethod<[bigint], Array<Material>>,
  'getSamplePapersByYear' : ActorMethod<[bigint], Array<SamplePaper>>,
  'getStats' : ActorMethod<
    [],
    {
      'totalAnnouncements' : bigint,
      'totalMaterials' : bigint,
      'totalPapers' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAnnouncement' : ActorMethod<[bigint, Announcement], undefined>,
  'updateMaterial' : ActorMethod<[bigint, Material], undefined>,
  'updateSamplePaper' : ActorMethod<[bigint, SamplePaper], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];